

########################################## CUSTOM site VARIABLES

title: Curso de Ciencia de Datos
description: Curso sobre Análisis de Datos, Machine Learning, Deep Learing, Big Data, Web Scraping, NLP, Minería de Procesos...
email: formacion@centic.es
github_username: CenticMurcia
twitter_username: CenticTwitt

########################################## URL

#url:                 # the base hostname for your site, e.g. http://example.com
baseurl: /curso-ciencia-datos # the subpath of your site, e.g. /blog

exclude: ['readme.md']


########################################## THEME

#remote_theme: pages-themes/cayman
theme: minima

header_pages:
  - about.md
  - references.md
  - youtube.md

#plugins:
#  - jekyll-feed
#  - jekyll-gist
#  - jekyll-octicons
#  - jekyll-github-metadata
#
#
#markdown: kramdown    # Default markdown processor in github
#use_math: True # Set this to true to get LaTeX math equation support
#highlighter: rouge
#markdown: kramdown
#kramdown:
#  math_engine: katex
#  input: GFM
#  auto_ids: true
#  hard_wrap: false
#  syntax_highlighter: rouge
